spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@172.66.150.5:1600:misbak
spring.datasource.username=complaints
spring.datasource.password=complaints
spring.jpa.show-sql=true

# Hibernate
hibernate.dialect: org.hibernate.dialect.OracleDialect
hibernate.show_sql: false
hibernate.hbm2ddl.auto: none

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext